/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.jdsb.hublancamentos.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LancamentoEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5155952438412671678L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LancamentoEvent\",\"namespace\":\"br.com.jdsb.hublancamentos.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"clientId\",\"type\":\"string\"},{\"name\":\"clientSegmento\",\"type\":\"string\"},{\"name\":\"valorLancamento\",\"type\":\"double\"},{\"name\":\"vencimentoLancamento\",\"type\":\"string\"},{\"name\":\"descontoLancamento\",\"type\":\"double\"},{\"name\":\"jurosLancamento\",\"type\":\"double\"},{\"name\":\"dataLancamento\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LancamentoEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LancamentoEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LancamentoEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LancamentoEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LancamentoEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LancamentoEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LancamentoEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LancamentoEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LancamentoEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence clientId;
  private java.lang.CharSequence clientSegmento;
  private double valorLancamento;
  private java.lang.CharSequence vencimentoLancamento;
  private double descontoLancamento;
  private double jurosLancamento;
  private java.lang.CharSequence dataLancamento;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LancamentoEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param clientId The new value for clientId
   * @param clientSegmento The new value for clientSegmento
   * @param valorLancamento The new value for valorLancamento
   * @param vencimentoLancamento The new value for vencimentoLancamento
   * @param descontoLancamento The new value for descontoLancamento
   * @param jurosLancamento The new value for jurosLancamento
   * @param dataLancamento The new value for dataLancamento
   */
  public LancamentoEvent(java.lang.CharSequence id, java.lang.CharSequence clientId, java.lang.CharSequence clientSegmento, java.lang.Double valorLancamento, java.lang.CharSequence vencimentoLancamento, java.lang.Double descontoLancamento, java.lang.Double jurosLancamento, java.lang.CharSequence dataLancamento) {
    this.id = id;
    this.clientId = clientId;
    this.clientSegmento = clientSegmento;
    this.valorLancamento = valorLancamento;
    this.vencimentoLancamento = vencimentoLancamento;
    this.descontoLancamento = descontoLancamento;
    this.jurosLancamento = jurosLancamento;
    this.dataLancamento = dataLancamento;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return clientId;
    case 2: return clientSegmento;
    case 3: return valorLancamento;
    case 4: return vencimentoLancamento;
    case 5: return descontoLancamento;
    case 6: return jurosLancamento;
    case 7: return dataLancamento;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: clientId = (java.lang.CharSequence)value$; break;
    case 2: clientSegmento = (java.lang.CharSequence)value$; break;
    case 3: valorLancamento = (java.lang.Double)value$; break;
    case 4: vencimentoLancamento = (java.lang.CharSequence)value$; break;
    case 5: descontoLancamento = (java.lang.Double)value$; break;
    case 6: jurosLancamento = (java.lang.Double)value$; break;
    case 7: dataLancamento = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'clientId' field.
   * @return The value of the 'clientId' field.
   */
  public java.lang.CharSequence getClientId() {
    return clientId;
  }


  /**
   * Sets the value of the 'clientId' field.
   * @param value the value to set.
   */
  public void setClientId(java.lang.CharSequence value) {
    this.clientId = value;
  }

  /**
   * Gets the value of the 'clientSegmento' field.
   * @return The value of the 'clientSegmento' field.
   */
  public java.lang.CharSequence getClientSegmento() {
    return clientSegmento;
  }


  /**
   * Sets the value of the 'clientSegmento' field.
   * @param value the value to set.
   */
  public void setClientSegmento(java.lang.CharSequence value) {
    this.clientSegmento = value;
  }

  /**
   * Gets the value of the 'valorLancamento' field.
   * @return The value of the 'valorLancamento' field.
   */
  public double getValorLancamento() {
    return valorLancamento;
  }


  /**
   * Sets the value of the 'valorLancamento' field.
   * @param value the value to set.
   */
  public void setValorLancamento(double value) {
    this.valorLancamento = value;
  }

  /**
   * Gets the value of the 'vencimentoLancamento' field.
   * @return The value of the 'vencimentoLancamento' field.
   */
  public java.lang.CharSequence getVencimentoLancamento() {
    return vencimentoLancamento;
  }


  /**
   * Sets the value of the 'vencimentoLancamento' field.
   * @param value the value to set.
   */
  public void setVencimentoLancamento(java.lang.CharSequence value) {
    this.vencimentoLancamento = value;
  }

  /**
   * Gets the value of the 'descontoLancamento' field.
   * @return The value of the 'descontoLancamento' field.
   */
  public double getDescontoLancamento() {
    return descontoLancamento;
  }


  /**
   * Sets the value of the 'descontoLancamento' field.
   * @param value the value to set.
   */
  public void setDescontoLancamento(double value) {
    this.descontoLancamento = value;
  }

  /**
   * Gets the value of the 'jurosLancamento' field.
   * @return The value of the 'jurosLancamento' field.
   */
  public double getJurosLancamento() {
    return jurosLancamento;
  }


  /**
   * Sets the value of the 'jurosLancamento' field.
   * @param value the value to set.
   */
  public void setJurosLancamento(double value) {
    this.jurosLancamento = value;
  }

  /**
   * Gets the value of the 'dataLancamento' field.
   * @return The value of the 'dataLancamento' field.
   */
  public java.lang.CharSequence getDataLancamento() {
    return dataLancamento;
  }


  /**
   * Sets the value of the 'dataLancamento' field.
   * @param value the value to set.
   */
  public void setDataLancamento(java.lang.CharSequence value) {
    this.dataLancamento = value;
  }

  /**
   * Creates a new LancamentoEvent RecordBuilder.
   * @return A new LancamentoEvent RecordBuilder
   */
  public static br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder newBuilder() {
    return new br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder();
  }

  /**
   * Creates a new LancamentoEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LancamentoEvent RecordBuilder
   */
  public static br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder newBuilder(br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder other) {
    if (other == null) {
      return new br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder();
    } else {
      return new br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder(other);
    }
  }

  /**
   * Creates a new LancamentoEvent RecordBuilder by copying an existing LancamentoEvent instance.
   * @param other The existing instance to copy.
   * @return A new LancamentoEvent RecordBuilder
   */
  public static br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder newBuilder(br.com.jdsb.hublancamentos.avro.LancamentoEvent other) {
    if (other == null) {
      return new br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder();
    } else {
      return new br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for LancamentoEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LancamentoEvent>
    implements org.apache.avro.data.RecordBuilder<LancamentoEvent> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence clientId;
    private java.lang.CharSequence clientSegmento;
    private double valorLancamento;
    private java.lang.CharSequence vencimentoLancamento;
    private double descontoLancamento;
    private double jurosLancamento;
    private java.lang.CharSequence dataLancamento;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.clientId)) {
        this.clientId = data().deepCopy(fields()[1].schema(), other.clientId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.clientSegmento)) {
        this.clientSegmento = data().deepCopy(fields()[2].schema(), other.clientSegmento);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.valorLancamento)) {
        this.valorLancamento = data().deepCopy(fields()[3].schema(), other.valorLancamento);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.vencimentoLancamento)) {
        this.vencimentoLancamento = data().deepCopy(fields()[4].schema(), other.vencimentoLancamento);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.descontoLancamento)) {
        this.descontoLancamento = data().deepCopy(fields()[5].schema(), other.descontoLancamento);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.jurosLancamento)) {
        this.jurosLancamento = data().deepCopy(fields()[6].schema(), other.jurosLancamento);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.dataLancamento)) {
        this.dataLancamento = data().deepCopy(fields()[7].schema(), other.dataLancamento);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing LancamentoEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.jdsb.hublancamentos.avro.LancamentoEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clientId)) {
        this.clientId = data().deepCopy(fields()[1].schema(), other.clientId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.clientSegmento)) {
        this.clientSegmento = data().deepCopy(fields()[2].schema(), other.clientSegmento);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.valorLancamento)) {
        this.valorLancamento = data().deepCopy(fields()[3].schema(), other.valorLancamento);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.vencimentoLancamento)) {
        this.vencimentoLancamento = data().deepCopy(fields()[4].schema(), other.vencimentoLancamento);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.descontoLancamento)) {
        this.descontoLancamento = data().deepCopy(fields()[5].schema(), other.descontoLancamento);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.jurosLancamento)) {
        this.jurosLancamento = data().deepCopy(fields()[6].schema(), other.jurosLancamento);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.dataLancamento)) {
        this.dataLancamento = data().deepCopy(fields()[7].schema(), other.dataLancamento);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'clientId' field.
      * @return The value.
      */
    public java.lang.CharSequence getClientId() {
      return clientId;
    }


    /**
      * Sets the value of the 'clientId' field.
      * @param value The value of 'clientId'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setClientId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.clientId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'clientId' field has been set.
      * @return True if the 'clientId' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'clientId' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearClientId() {
      clientId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'clientSegmento' field.
      * @return The value.
      */
    public java.lang.CharSequence getClientSegmento() {
      return clientSegmento;
    }


    /**
      * Sets the value of the 'clientSegmento' field.
      * @param value The value of 'clientSegmento'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setClientSegmento(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.clientSegmento = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'clientSegmento' field has been set.
      * @return True if the 'clientSegmento' field has been set, false otherwise.
      */
    public boolean hasClientSegmento() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'clientSegmento' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearClientSegmento() {
      clientSegmento = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'valorLancamento' field.
      * @return The value.
      */
    public double getValorLancamento() {
      return valorLancamento;
    }


    /**
      * Sets the value of the 'valorLancamento' field.
      * @param value The value of 'valorLancamento'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setValorLancamento(double value) {
      validate(fields()[3], value);
      this.valorLancamento = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'valorLancamento' field has been set.
      * @return True if the 'valorLancamento' field has been set, false otherwise.
      */
    public boolean hasValorLancamento() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'valorLancamento' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearValorLancamento() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'vencimentoLancamento' field.
      * @return The value.
      */
    public java.lang.CharSequence getVencimentoLancamento() {
      return vencimentoLancamento;
    }


    /**
      * Sets the value of the 'vencimentoLancamento' field.
      * @param value The value of 'vencimentoLancamento'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setVencimentoLancamento(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.vencimentoLancamento = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'vencimentoLancamento' field has been set.
      * @return True if the 'vencimentoLancamento' field has been set, false otherwise.
      */
    public boolean hasVencimentoLancamento() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'vencimentoLancamento' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearVencimentoLancamento() {
      vencimentoLancamento = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'descontoLancamento' field.
      * @return The value.
      */
    public double getDescontoLancamento() {
      return descontoLancamento;
    }


    /**
      * Sets the value of the 'descontoLancamento' field.
      * @param value The value of 'descontoLancamento'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setDescontoLancamento(double value) {
      validate(fields()[5], value);
      this.descontoLancamento = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'descontoLancamento' field has been set.
      * @return True if the 'descontoLancamento' field has been set, false otherwise.
      */
    public boolean hasDescontoLancamento() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'descontoLancamento' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearDescontoLancamento() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'jurosLancamento' field.
      * @return The value.
      */
    public double getJurosLancamento() {
      return jurosLancamento;
    }


    /**
      * Sets the value of the 'jurosLancamento' field.
      * @param value The value of 'jurosLancamento'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setJurosLancamento(double value) {
      validate(fields()[6], value);
      this.jurosLancamento = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'jurosLancamento' field has been set.
      * @return True if the 'jurosLancamento' field has been set, false otherwise.
      */
    public boolean hasJurosLancamento() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'jurosLancamento' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearJurosLancamento() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataLancamento' field.
      * @return The value.
      */
    public java.lang.CharSequence getDataLancamento() {
      return dataLancamento;
    }


    /**
      * Sets the value of the 'dataLancamento' field.
      * @param value The value of 'dataLancamento'.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder setDataLancamento(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.dataLancamento = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'dataLancamento' field has been set.
      * @return True if the 'dataLancamento' field has been set, false otherwise.
      */
    public boolean hasDataLancamento() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'dataLancamento' field.
      * @return This builder.
      */
    public br.com.jdsb.hublancamentos.avro.LancamentoEvent.Builder clearDataLancamento() {
      dataLancamento = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LancamentoEvent build() {
      try {
        LancamentoEvent record = new LancamentoEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.clientId = fieldSetFlags()[1] ? this.clientId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.clientSegmento = fieldSetFlags()[2] ? this.clientSegmento : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.valorLancamento = fieldSetFlags()[3] ? this.valorLancamento : (java.lang.Double) defaultValue(fields()[3]);
        record.vencimentoLancamento = fieldSetFlags()[4] ? this.vencimentoLancamento : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.descontoLancamento = fieldSetFlags()[5] ? this.descontoLancamento : (java.lang.Double) defaultValue(fields()[5]);
        record.jurosLancamento = fieldSetFlags()[6] ? this.jurosLancamento : (java.lang.Double) defaultValue(fields()[6]);
        record.dataLancamento = fieldSetFlags()[7] ? this.dataLancamento : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LancamentoEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<LancamentoEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LancamentoEvent>
    READER$ = (org.apache.avro.io.DatumReader<LancamentoEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.clientId);

    out.writeString(this.clientSegmento);

    out.writeDouble(this.valorLancamento);

    out.writeString(this.vencimentoLancamento);

    out.writeDouble(this.descontoLancamento);

    out.writeDouble(this.jurosLancamento);

    out.writeString(this.dataLancamento);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.clientId = in.readString(this.clientId instanceof Utf8 ? (Utf8)this.clientId : null);

      this.clientSegmento = in.readString(this.clientSegmento instanceof Utf8 ? (Utf8)this.clientSegmento : null);

      this.valorLancamento = in.readDouble();

      this.vencimentoLancamento = in.readString(this.vencimentoLancamento instanceof Utf8 ? (Utf8)this.vencimentoLancamento : null);

      this.descontoLancamento = in.readDouble();

      this.jurosLancamento = in.readDouble();

      this.dataLancamento = in.readString(this.dataLancamento instanceof Utf8 ? (Utf8)this.dataLancamento : null);

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.clientId = in.readString(this.clientId instanceof Utf8 ? (Utf8)this.clientId : null);
          break;

        case 2:
          this.clientSegmento = in.readString(this.clientSegmento instanceof Utf8 ? (Utf8)this.clientSegmento : null);
          break;

        case 3:
          this.valorLancamento = in.readDouble();
          break;

        case 4:
          this.vencimentoLancamento = in.readString(this.vencimentoLancamento instanceof Utf8 ? (Utf8)this.vencimentoLancamento : null);
          break;

        case 5:
          this.descontoLancamento = in.readDouble();
          break;

        case 6:
          this.jurosLancamento = in.readDouble();
          break;

        case 7:
          this.dataLancamento = in.readString(this.dataLancamento instanceof Utf8 ? (Utf8)this.dataLancamento : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










