name: Build, Deploy Infra & App

on:
  push:
    branches:
      - main

jobs:
  decidir:
    runs-on: ubuntu-latest
    outputs:
      destroy_flag: ${{ steps.check.outputs.destroy_flag }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Ler projeto.yml
        id: check
        run: |
          flag=$(yq '.destroy' projeto.yml)
          echo "destroy_flag=$flag" >> $GITHUB_OUTPUT

  build-push-deploy:
    needs: decidir
    runs-on: ubuntu-latest
    if: needs.decidir.outputs.destroy_flag == 'true' || needs.decidir.outputs.destroy_flag == 'false'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login no ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build da imagem Docker
        run: |
          IMAGE_TAG=latest
          docker build -t ${{ steps.login-ecr.outputs.registry }}/hub-lancamentos:$IMAGE_TAG .

      - name: Push da imagem para o ECR
        run: |
          IMAGE_TAG=latest
          docker push ${{ steps.login-ecr.outputs.registry }}/hub-lancamentos:$IMAGE_TAG

  terraform:
    needs: [decidir]
    runs-on: ubuntu-latest
    if: needs.decidir.outputs.destroy_flag == 'true' || needs.decidir.outputs.destroy_flag == 'false'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        run: terraform init
        working-directory: infra

      - name: Terraform Destroy
        if: needs.decidir.outputs.destroy_flag == 'true'
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
        working-directory: infra

      - name: Terraform Apply
        if: needs.decidir.outputs.destroy_flag == 'false' || needs.decidir.outputs.destroy_flag == ''
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: infra
